server.port: 8082

spring:
  application:
    name: ms-notifications-management

springdoc:
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'

api-swagger:
  url-dev: 'http://localhost:${server.port}'
  description-dev: 'Development server'
  url-prod: 'https://api.alkz.com/notifications-management'
  description-prod: 'Production server'
  contact-name: 'Support Alkz Team'
  contact-email: 'support@alkz.com'
  contact-url: 'https://alkz.com'
  license-name: 'MIT License'
  license-url: 'https://opensource.org/licenses/MIT'
  info-title: 'API Documentation for ms-notifications-management'
  info-version: '1.0.0'
  info-description: 'This is the API documentation for the notifications management microservice.'
  info-terms-of-service: 'https://alejdaf.com/terms'
  security-scheme-name: 'Authorization'
  security-scheme-description: 'Use the JWT token obtained after login to authorize requests. Format: {token}'
  security-scheme-scheme: 'bearer'
  security-scheme-bearer-format: 'JWT'