plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0' apply false
	id 'io.spring.dependency-management' version '1.1.7' apply false
}

allprojects {
	group = 'akz'
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

subprojects {
	apply plugin: "java"
    apply plugin: "io.spring.dependency-management"

    repositories {
        mavenCentral()
        mavenLocal()
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

	dependencies {		
		implementation 'org.springframework.boot:spring-boot-starter-webmvc'
        implementation 'alejdaf:common-utils:0.0.1'
        implementation group: 'org.springdoc', name: 'springdoc-openapi-starter-webmvc-ui', version: '2.8.12'

        compileOnly 'org.projectlombok:lombok'
		
		annotationProcessor 'org.projectlombok:lombok'
		
		testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
		
		testCompileOnly 'org.projectlombok:lombok'
		
		testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
		
		testAnnotationProcessor 'org.projectlombok:lombok'	
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
