plugins {
	id 'java'
	id 'org.springframework.boot'
	id 'io.spring.dependency-management'
}

version = '0.0.1-SNAPSHOT'
description = 'Microservice for notifications management'


repositories {
	mavenCentral()
}

dependencies {
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
}

tasks.named('test') {
	useJUnitPlatform()
}
